# Name of our workflow
name: Daily Repository Update

# When to run the workflow
on:
  schedule:
    # This will run at 10:00 AM UTC every day
    - cron: '0 10 * * *'
  # Also allow manual triggers
  workflow_dispatch:

# Add permissions block here
permissions:
  contents: write    # This is crucial - allows writing to the repository

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Get a copy of our repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1   # Only fetch the last commit to speed up checkout

      # Step 2: Create a simple update (includes your email as required)
      - name: Create daily update with 22f3002134@ds.study.iitm.ac.in
        run: |
          # Create a timestamp in the file
          echo "Repository updated on: $(date)" > update.txt
          
      # Step 3: Commit and push the changes
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add update.txt
          git commit -m "Daily automated update [skip ci]"
          git push origin HEAD:main
